services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiSettings__BaseUrl=${API_BASE_URL:-https://apiburguer.ribeiroworkes.com}
    restart: unless-stopped
